# Generated by Django 4.0 on 2022-01-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='phoneName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneName', models.CharField(max_length=200)),
                ('avatar', models.ImageField(default='image.png', null=True, upload_to='')),
                ('names', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='NETWORK', max_length=200, verbose_name='NETWORK')),
                ('technology', models.CharField(blank=True, max_length=200, verbose_name='Technology')),
                ('twogBands', models.CharField(blank=True, max_length=200, verbose_name='2G bands')),
                ('threegBands', models.CharField(blank=True, max_length=200, verbose_name='3G bands')),
                ('fourgBands', models.CharField(blank=True, max_length=200, verbose_name='4G bands')),
                ('speed', models.CharField(blank=True, max_length=200, verbose_name='Speed')),
                ('launch', models.CharField(default='LAUNCH', max_length=200, verbose_name='LAUNCH')),
                ('announced', models.CharField(blank=True, max_length=200, verbose_name='Announced')),
                ('status', models.CharField(blank=True, max_length=200, verbose_name='Status')),
                ('body', models.CharField(default='BODY', max_length=200, verbose_name='BODY')),
                ('dimensions', models.CharField(blank=True, max_length=200, verbose_name='Dimensions')),
                ('weight', models.CharField(blank=True, max_length=200, verbose_name='Weight')),
                ('build', models.CharField(blank=True, max_length=200, verbose_name='Build')),
                ('sim', models.CharField(blank=True, max_length=200, verbose_name='SIM')),
                ('rgb', models.CharField(blank=True, max_length=200, verbose_name='RGB')),
                ('display', models.CharField(default='DISPLAY', max_length=200, verbose_name='DISPLAY')),
                ('typess', models.CharField(blank=True, max_length=200, verbose_name='Type')),
                ('size', models.CharField(blank=True, max_length=200, verbose_name='Size')),
                ('resolution', models.CharField(blank=True, max_length=200, verbose_name='Resolution')),
                ('protection', models.CharField(blank=True, max_length=200, verbose_name='Protection')),
                ('platform', models.CharField(default='PLATFORM', max_length=200, verbose_name='PLATFORM')),
                ('os', models.CharField(blank=True, max_length=200, verbose_name='OS')),
                ('chipset', models.CharField(blank=True, max_length=200, verbose_name='Chipset')),
                ('cpu', models.CharField(blank=True, max_length=200, verbose_name='CPU')),
                ('gpu', models.CharField(blank=True, max_length=200, verbose_name='GPU')),
                ('memory', models.CharField(default='MEMORY', max_length=200, verbose_name='MEMORY')),
                ('cardSlot', models.CharField(blank=True, max_length=200, verbose_name='Card slot')),
                ('internal', models.CharField(blank=True, max_length=200, verbose_name='Internal')),
                ('storage', models.CharField(blank=True, max_length=200, verbose_name='Storage')),
                ('mainCamera', models.CharField(default='MAIN CAMERA', max_length=200, verbose_name='MAIN CAMERA')),
                ('dual', models.CharField(blank=True, max_length=200, verbose_name='Dual')),
                ('video', models.CharField(blank=True, max_length=200, verbose_name='Video')),
                ('selfieCamera', models.CharField(default='SELFIE CAMERA', max_length=200, verbose_name='SELFIE CAMERA')),
                ('selfieSingle', models.CharField(blank=True, max_length=200, verbose_name='Single')),
                ('selfieFeatures', models.CharField(blank=True, max_length=200, verbose_name='Features')),
                ('selfieVideo', models.CharField(blank=True, max_length=200, verbose_name='video')),
                ('comms', models.CharField(default='COMMS', max_length=200, verbose_name='COMMS')),
                ('wlan', models.CharField(blank=True, max_length=200, verbose_name='WLAN')),
                ('bluetooth', models.CharField(blank=True, max_length=200, verbose_name='Bluetooth')),
                ('gps', models.CharField(blank=True, max_length=200, verbose_name='GPS')),
                ('nfc', models.CharField(blank=True, max_length=200, verbose_name='NFC')),
                ('radio', models.CharField(blank=True, max_length=200, verbose_name='Radio')),
                ('usb', models.CharField(blank=True, max_length=200, verbose_name='USB')),
                ('features', models.CharField(default='FEATURES', max_length=200, verbose_name='FEATURES')),
                ('Sensors', models.CharField(blank=True, max_length=200, verbose_name='Sensors')),
                ('battery', models.CharField(default='BATTERY', max_length=200, verbose_name='BATTERY')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='Type')),
                ('charging', models.TextField(blank=True, max_length=200, verbose_name='Charging')),
                ('misc', models.CharField(default='MISC', max_length=200, verbose_name='MISC')),
                ('colors', models.CharField(blank=True, max_length=200, verbose_name='Colors')),
                ('modelss', models.CharField(blank=True, max_length=200, verbose_name='Models')),
                ('price', models.CharField(blank=True, max_length=200, verbose_name='Price')),
                ('tests', models.CharField(default='TESTS', max_length=200, verbose_name='TESTS')),
                ('performance', models.CharField(blank=True, max_length=200, verbose_name='Performance')),
                ('displayTest', models.CharField(blank=True, max_length=200, verbose_name='Display Test')),
                ('camera', models.CharField(blank=True, max_length=200, verbose_name='Camera')),
                ('loudspeaker', models.CharField(blank=True, max_length=200, verbose_name='Loudspeaker')),
                ('battery_life', models.CharField(blank=True, max_length=200, verbose_name='Battery life')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.phonename')),
            ],
        ),
    ]
