# Generated by Django 4.0 on 2022-01-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_phone_fivegbands'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='mainfeatures',
            field=models.CharField(blank=True, max_length=200, verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='dual',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dual/Triple'),
        ),
    ]
