# Generated by Django 4.0 on 2022-01-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_phone_frequency_phone_jack_phone_loudspeakers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='sar',
            field=models.CharField(blank=True, max_length=200, verbose_name='SAR'),
        ),
        migrations.AddField(
            model_name='phone',
            name='sarEu',
            field=models.CharField(blank=True, max_length=200, verbose_name='SAR EU'),
        ),
    ]
