# Generated by Django 4.0 on 2022-01-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_phone_sar_phone_sareu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='performance',
            field=models.TextField(blank=True, max_length=200, verbose_name='Performance'),
        ),
    ]
